repos:
  - repo: "git@github.com:PyCQA/autoflake.git"
    rev: v2.0.0
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--no-sort-keys"
          - "--autofix"
        exclude: Pipfile.lock
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
  - repo: "https://github.com/pycqa/isort"
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: "https://github.com/psf/black"
    rev: 22.12.0
    hooks:
      - id: black
  - repo: "https://github.com/pycqa/flake8"
    rev: 6.0.0
    hooks:
      - id: flake8
  # - repo: "https://github.com/pre-commit/mirrors-mypy"
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: ./pre-commit-mypy.sh
        language: script
        require_serial: true # (optional: default false) if true this hook will execute using a single process instead of in parallel.
  - repo: "https://github.com/PyCQA/bandit"
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - "-c"
          - "pyproject.toml"
        additional_dependencies:
          - "bandit[toml]"
