version: "3.9"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
    volumes:
      - azurite-data:/data

  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile.app
      target: dev
      secrets:
        - PIP_INDEX_URL
      ssh:
        - default
    env_file: app/.env
    ports:
      - 8000:80

volumes:
  azurite-data:

secrets:
  PIP_INDEX_URL:
    environment: PIP_INDEX_URL
