[tool.mypy]
plugins = "pydantic.mypy"
ignore_missing_imports = true
python_version = "3.10"

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
ensure_newline_before_comments=true
line_length=88
force_sort_within_sections=true
order_by_type=false
case_sensitive=false
reverse_relative=false
sort_relative_in_force_sorted_sections=false
profile="appnexus"
overwrite_in_place=true
sections=["FUTURE","STDLIB","INFRA","INSTALLED","FIRSTPARTY","THIRDPARTY","LOCALFOLDER"]
known_infra=[]
known_installed=["azure", "opencensus", "starlette","dependency_injector","fastapi","uvicorn","pydantic","httpx","tenacity","rollbar","fastapi-utils","pytz","arrow","pytest","pytest-random-order","faker","pytest","freezegun","importlib_resources","importlib_metadata","furl", "nano_shared"]
known_first_party=["shared","config", "log_config", "dependencies","models","queries","api","routers","services","utils", "schemas", "handlers", "exceptions", "middleware"]
known_third_party=""
known_local_folder=""
skip_glob = [".git", ".venv"]


[tool.bandit]
exclude_dirs = ["tests", "docs", "helm"]
skips = ["B104", "B608"]
